{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "18a6e47e-ceba-469c-91ab-b4d10b74262e",
   "metadata": {},
   "source": [
    "### Neural Network from scratch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "159cfc86-748a-40c6-bccf-c00e7eb1c577",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch:  10 | Loss: 0.3986 | Acc Train: 0.8500 | Acc Test: 0.8333\n",
      "Epoch:  20 | Loss: 0.2817 | Acc Train: 0.9000 | Acc Test: 0.9000\n",
      "Epoch:  30 | Loss: 0.2335 | Acc Train: 0.9333 | Acc Test: 0.9333\n",
      "Epoch:  40 | Loss: 0.1897 | Acc Train: 0.9500 | Acc Test: 0.9333\n",
      "Epoch:  50 | Loss: 0.1516 | Acc Train: 0.9417 | Acc Test: 0.9333\n",
      "Epoch:  60 | Loss: 0.1307 | Acc Train: 0.9583 | Acc Test: 0.9333\n",
      "Epoch:  70 | Loss: 0.1171 | Acc Train: 0.9583 | Acc Test: 0.9333\n",
      "Epoch:  80 | Loss: 0.1094 | Acc Train: 0.9583 | Acc Test: 0.9333\n",
      "Epoch:  90 | Loss: 0.0967 | Acc Train: 0.9667 | Acc Test: 0.9333\n",
      "Epoch: 100 | Loss: 0.0888 | Acc Train: 0.9667 | Acc Test: 0.9333\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from sklearn import datasets\n",
    "\n",
    "# 1. Initialize hyperparameters\n",
    "input_dim, h_dim, out_dim = 4, 10, 3  # Increased h_dim for better capacity\n",
    "batch_size = 16\n",
    "num_epoch = 100\n",
    "alpha = 0.05\n",
    "\n",
    "# 2. Load and prepare dataset\n",
    "iris = datasets.load_iris()\n",
    "X = iris.data\n",
    "y = iris.target\n",
    "\n",
    "# Neural networks converge much faster when input features are on the same scale.\n",
    "X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)\n",
    "\n",
    "def to_one_hot(y, out_dim):\n",
    "    return np.eye(out_dim)[y]\n",
    "\n",
    "Y_oh = to_one_hot(y, out_dim)\n",
    "\n",
    "# Initial shuffle and split\n",
    "indices = np.arange(len(X))\n",
    "np.random.shuffle(indices)\n",
    "X, Y_oh = X[indices], Y_oh[indices]\n",
    "\n",
    "X_train, y_train = X[:120], Y_oh[:120]\n",
    "X_test, y_test = X[120:], Y_oh[120:]\n",
    "\n",
    "# 3. Initialize weights and biases\n",
    "# Use He Initialization: np.sqrt(2/n) helps prevent vanishing/exploding gradients.\n",
    "W1 = np.random.randn(input_dim, h_dim) * np.sqrt(2/input_dim)\n",
    "B1 = np.zeros((1, h_dim))\n",
    "W2 = np.random.randn(h_dim, out_dim) * np.sqrt(2/h_dim)\n",
    "B2 = np.zeros((1, out_dim))\n",
    "\n",
    "def ReLU(X):\n",
    "    return np.maximum(X, 0)\n",
    "\n",
    "def softmax(X):\n",
    "    # axis=1 is CRITICAL for mini-batches to normalize across classes, not samples.\n",
    "    exps = np.exp(X - np.max(X, axis=1, keepdims=True))\n",
    "    return exps / np.sum(exps, axis=1, keepdims=True)\n",
    "\n",
    "def loss(Y, Z):\n",
    "    # Cross-Entropy loss: we add 1e-15 to avoid log(0) which results in NaN.\n",
    "    return np.mean(-np.sum(Y * np.log(Z + 1e-15), axis=1))\n",
    "\n",
    "def feedforward(W1, W2, B1, B2, X):\n",
    "    A1 = X @ W1 + B1\n",
    "    H1 = ReLU(A1)\n",
    "    A2 = H1 @ W2 + B2\n",
    "    Z = softmax(A2)\n",
    "    return A1, H1, A2, Z\n",
    "\n",
    "def Backward(A1, H1, A2, Z, Y, X):\n",
    "    m = X.shape[0] # Use dynamic batch size (last batch might be smaller)\n",
    "    \n",
    "    dE_dA2 = Z - Y         \n",
    "    dE_dW2 = (H1.T @ dE_dA2) / m  # CRITICAL: Average gradient by dividing by batch size m\n",
    "    dE_dB2 = np.sum(dE_dA2, axis=0, keepdims=True) / m      \n",
    "    \n",
    "    dE_dH1 = dE_dA2 @ W2.T   \n",
    "    dE_dA1 = dE_dH1 * (A1 > 0) # ReLU derivative\n",
    "    \n",
    "    dE_dW1 = (X.T @ dE_dA1) / m\n",
    "    dE_dB1 = np.sum(dE_dA1, axis=0, keepdims=True) / m       \n",
    "    return dE_dW2, dE_dW1, dE_dB2, dE_dB1\n",
    "\n",
    "def Update(dW2, dW1, dB2, dB1, W1, W2, B1, B2):\n",
    "    W1 -= alpha * dW1\n",
    "    W2 -= alpha * dW2\n",
    "    B1 -= alpha * dB1\n",
    "    B2 -= alpha * dB2\n",
    "    return W1, W2, B1, B2\n",
    "\n",
    "def predict(X):\n",
    "    _, _, _, Z = feedforward(W1, W2, B1, B2, X)\n",
    "    return np.argmax(Z, axis=1)\n",
    "\n",
    "def accuracy(x_data, y_data):\n",
    "    prediction = predict(x_data)\n",
    "    y_true = np.argmax(y_data, axis=1)\n",
    "    return np.mean(prediction == y_true)\n",
    "\n",
    "# 4. Training Loop\n",
    "for epoch in range(num_epoch):\n",
    "    # Shuffle training data every epoch to improve generalization\n",
    "    indices = np.arange(len(X_train))\n",
    "    np.random.shuffle(indices)\n",
    "    X_train, y_train = X_train[indices], y_train[indices]\n",
    "    \n",
    "    epoch_losses = [] # Reset loss list every epoch\n",
    "      \n",
    "    for i in range(0, len(X_train), batch_size):\n",
    "        X_sample = X_train[i:i+batch_size]\n",
    "        Y_sample = y_train[i:i+batch_size]\n",
    "        \n",
    "        # Forward -> Backward -> Update\n",
    "        A1, H1, A2, Z = feedforward(W1, W2, B1, B2, X_sample)\n",
    "        E = loss(Y_sample, Z)\n",
    "        dW2, dW1, dB2, dB1 = Backward(A1, H1, A2, Z, Y_sample, X_sample)\n",
    "        W1, W2, B1, B2 = Update(dW2, dW1, dB2, dB1, W1, W2, B1, B2)\n",
    "        \n",
    "        epoch_losses.append(E)\n",
    "\n",
    "    if (epoch + 1) % 10 == 0:\n",
    "        acc_tr = accuracy(X_train, y_train)\n",
    "        acc_ts = accuracy(X_test, y_test)\n",
    "        print(f\"Epoch: {epoch+1:3} | Loss: {np.mean(epoch_losses):.4f} | Acc Train: {acc_tr:.4f} | Acc Test: {acc_ts:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a6e8ba1c-baec-42db-8455-8eede910ad46",
   "metadata": {},
   "source": [
    "### Neural Network with Pytorch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "179e4af9-c31d-421f-801a-bc13005ff9b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epochs [ 10/100] | Loss: 4.4158 | Train Acc: 0.8833 | Test Acc: 0.9000\n",
      "Epochs [ 20/100] | Loss: 2.6744 | Train Acc: 0.9167 | Test Acc: 1.0000\n",
      "Epochs [ 30/100] | Loss: 2.0401 | Train Acc: 0.9333 | Test Acc: 1.0000\n",
      "Epochs [ 40/100] | Loss: 1.7706 | Train Acc: 0.9500 | Test Acc: 1.0000\n",
      "Epochs [ 50/100] | Loss: 1.4400 | Train Acc: 0.9583 | Test Acc: 1.0000\n",
      "Epochs [ 60/100] | Loss: 1.2884 | Train Acc: 0.9583 | Test Acc: 1.0000\n",
      "Epochs [ 70/100] | Loss: 1.1108 | Train Acc: 0.9667 | Test Acc: 1.0000\n",
      "Epochs [ 80/100] | Loss: 1.0250 | Train Acc: 0.9667 | Test Acc: 1.0000\n",
      "Epochs [ 90/100] | Loss: 0.9200 | Train Acc: 0.9667 | Test Acc: 1.0000\n",
      "Epochs [100/100] | Loss: 0.8890 | Train Acc: 0.9667 | Test Acc: 1.0000\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader, TensorDataset\n",
    "from sklearn import datasets\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# 1. Loading Data \n",
    "iris = datasets.load_iris()\n",
    "X = iris.data\n",
    "y = iris.target\n",
    "\n",
    "# split into train and test\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\n",
    "\n",
    "# Standardizing data\n",
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)  # only transforem\n",
    "\n",
    "# Convert Numpy arrays to Pytorch Tensor\n",
    "# X is float32, y is int64 (LongTensor)\n",
    "X_train_tensor = torch.tensor(X_train, dtype=torch.float32)\n",
    "y_train_tensor = torch.tensor(y_train, dtype=torch.int64)\n",
    "X_test_tensor = torch.tensor(X_test, dtype=torch.float32)\n",
    "y_test_tensor = torch.tensor(y_test, dtype=torch.int64)\n",
    "\n",
    "# Create Dataloader (Handle batches and shuffling automatically)\n",
    "train_dataset = TensorDataset(X_train_tensor, y_train_tensor)\n",
    "train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last=True)\n",
    "\n",
    "# 2. Define the Neural Network Architecture\n",
    "class IrisNet(nn.Module):\n",
    "    def __init__(self, input_dim, h_dim, out_dim):\n",
    "        super(IrisNet, self).__init__()\n",
    "        # nn.Linear automatically initializes weights and biases\n",
    "        self.fc1 = nn.Linear(input_dim, h_dim)\n",
    "        self.relu = nn.ReLU()\n",
    "        self.fc2 = nn.Linear(h_dim, out_dim)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.fc1(x)\n",
    "        x = self.relu(x)\n",
    "        x = self.fc2(x)\n",
    "        # Note: No Softmax here!\n",
    "        # nn.CrossEntropyloss in Pytorch combines Softmax and Loss in one function\n",
    "        return x\n",
    "\n",
    "# 3 Initialize Model, Loss, and Optimizer\n",
    "model = IrisNet(input_dim=4, h_dim=5, out_dim=3)\n",
    "criterion = nn.CrossEntropyLoss()  # loss fnction\n",
    "optimizer = optim.SGD(model.parameters(), lr=0.05)\n",
    "\n",
    "# 4. Training Looop\n",
    "num_epochs=100\n",
    "\n",
    "for epoch in range(num_epochs):\n",
    "    model.train() \n",
    "    epoch_losses = 0\n",
    "\n",
    "    for X_batch, y_batch in train_loader:\n",
    "        # Forward Pass\n",
    "        outputs = model(X_batch)\n",
    "        loss = criterion(outputs, y_batch)\n",
    "\n",
    "        # Backward Pass \n",
    "        optimizer.zero_grad() # Clear previous gradients\n",
    "        loss.backward()       # Automatically calculate all derivatives (dW, dB)\n",
    "\n",
    "        # Update Weights\n",
    "        optimizer.step()      # W = W - lr * dW \n",
    "\n",
    "        epoch_losses += loss.item()\n",
    "\n",
    "    if (epoch+1) % 10 == 0:\n",
    "        model.eval() # Set model to evaluation mode\n",
    "        with torch.no_grad():\n",
    "            train_preds = model(X_train_tensor)  # count accuracy on train\n",
    "            train_acc = (torch.argmax(train_preds, dim=1)==y_train_tensor).float().mean() \n",
    "\n",
    "            test_preds = model(X_test_tensor)# count accuracy on test\n",
    "            test_acc = (torch.argmax(test_preds, dim=1)==y_test_tensor).float().mean()\n",
    "\n",
    "        print(f\"Epochs [{epoch+1:3}/{num_epochs:3}] | Loss: {epoch_losses:.4f} | Train Acc: {train_acc:.4f} | Test Acc: {test_acc:.4f}\")\n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "128b7284-e2be-4ef8-bde6-4367f4978e01",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (GPU)",
   "language": "python",
   "name": "gpu-env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
